{
	"version": 1668917688,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tile-sheet0.png",
		"images/tile-sheet1.png",
		"images/tile-sheet2.png",
		"images/mango-sheet0.png",
		"images/mango-sheet1.png",
		"images/mango-sheet2.png",
		"images/playerbox-sheet0.png",
		"images/leftb-sheet0.png",
		"images/rightb-sheet0.png",
		"images/up-sheet0.png",
		"images/tilemap.png",
		"images/wall-sheet0.png",
		"media/swoosh1.m4a",
		"media/swoosh1.ogg",
		"media/scratch1.m4a",
		"media/scratch1.ogg",
		"media/mattoglseby - 7.m4a",
		"media/mattoglseby - 7.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}